### ISSUE TITLE
Seperate files for header and footer?

### ISSUE THREAD

**Issue by AutogolazzoJr** [lighthouse64/TSA_Website#12]
Why are there separate files for header and footer? I'd prefer each webpage to be one php document.

**Comment by DarinMao** [comment]
PHP is server side code, so it is executed before the site is even delivered to the user's browser. 
Why is this relevant? When you look at index.php, it is actually one php document. The include()'s take the content of the header and footer and actually "paste" them into the document.
Why are we doing this? This way, we can put `<?php include("header.php"); ?>` at the top of each page and `<?php include("footer.php"); ?>` at the bottom of the page, and it will insert the header and footer. By doing it this way, any changes you want to make to the header and footer can be done from just one file, instead of editing EVERY SINGLE FRICKIN' PAGE!
